-- MySQL Script generated by MySQL Workbench
-- Wed Oct 28 22:14:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`area` ;

CREATE TABLE IF NOT EXISTS `mydb`.`area` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profissional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`profissional` ;

CREATE TABLE IF NOT EXISTS `mydb`.`profissional` (
  `id` INT NOT NULL,
  `nome` VARCHAR(30) NULL,
  `idade` INT(2) NULL,
  `escolaridade` ENUM('0', '1', '2', '3', '4', '5') NULL,
  `area_id` INT NOT NULL,
  `preco` INT(6) NULL,
  `status` ENUM('Disponivel', 'Ocupado') NULL,
  `profissionalcol1` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_profissional_area1`
    FOREIGN KEY (`area_id`)
    REFERENCES `mydb`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_profissional_area1_idx` ON `mydb`.`profissional` (`area_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`formacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`formacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`formacao` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(100) NULL,
  `valor` INT(6) NULL,
  `profissional_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_formacao_profissional1`
    FOREIGN KEY (`profissional_id`)
    REFERENCES `mydb`.`profissional` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_formacao_profissional1_idx` ON `mydb`.`formacao` (`profissional_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`contratante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contratante` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contratante` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `detalhes` VARCHAR(100) NULL,
  `imagem` VARCHAR(50) NULL,
  `contratantecol` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vaga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`vaga` ;

CREATE TABLE IF NOT EXISTS `mydb`.`vaga` (
  `profissional_id` INT NOT NULL,
  `contratante_id` INT NOT NULL,
  `area_id` INT NOT NULL,
  `valor` INT(6) NULL,
  `nome` VARCHAR(50) NULL,
  `descricao` VARCHAR(100) NULL,
  `dataInicial` DATE NULL,
  `status` ENUM('Disponivel', 'Negociando', 'fechado') NULL,
  PRIMARY KEY (`profissional_id`, `contratante_id`),
  CONSTRAINT `fk_profissional_has_contratante_profissional`
    FOREIGN KEY (`profissional_id`)
    REFERENCES `mydb`.`profissional` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profissional_has_contratante_contratante1`
    FOREIGN KEY (`contratante_id`)
    REFERENCES `mydb`.`contratante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vaga_area1`
    FOREIGN KEY (`area_id`)
    REFERENCES `mydb`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_profissional_has_contratante_contratante1_idx` ON `mydb`.`vaga` (`contratante_id` ASC) VISIBLE;

CREATE INDEX `fk_profissional_has_contratante_profissional_idx` ON `mydb`.`vaga` (`profissional_id` ASC) VISIBLE;

CREATE INDEX `fk_vaga_area1_idx` ON `mydb`.`vaga` (`area_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
