-- MySQL Script generated by MySQL Workbench
-- Mon Nov 16 19:45:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`transacionador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transacionador` (
  `id` INT NOT NULL,
  `nome` VARCHAR(30) NULL,
  `dataNascimento` DATE NULL,
  `escolaridade` ENUM('0', '1', '2', '3', '4', '5') NULL,
  `precoHora` INT(6) NULL,
  `status` ENUM('Disponivel', 'Ocupado') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`formacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`formacao` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`area` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Projeto` (
  `id` INT NOT NULL,
  `valor` INT(6) NULL,
  `nome` VARCHAR(50) NULL,
  `descricao` VARCHAR(100) NULL,
  `dataInicial` DATE NULL,
  `status` ENUM('Disponivel', 'Negociando', 'fechado') NULL,
  `codigoDoContratante` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Projeto_profissional1`
    FOREIGN KEY (`codigoDoContratante`)
    REFERENCES `mydb`.`transacionador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Projeto_profissional1_idx` ON `mydb`.`Projeto` (`codigoDoContratante` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`formacaoDoProfissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`formacaoDoProfissional` (
  `formacaoId` INT NOT NULL,
  `profissionalId` INT NOT NULL,
  PRIMARY KEY (`formacaoId`, `profissionalId`),
  CONSTRAINT `fk_formacao_has_profissional_formacao1`
    FOREIGN KEY (`formacaoId`)
    REFERENCES `mydb`.`formacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formacao_has_profissional_profissional1`
    FOREIGN KEY (`profissionalId`)
    REFERENCES `mydb`.`transacionador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_formacao_has_profissional_profissional1_idx` ON `mydb`.`formacaoDoProfissional` (`profissionalId` ASC) VISIBLE;

CREATE INDEX `fk_formacao_has_profissional_formacao1_idx` ON `mydb`.`formacaoDoProfissional` (`formacaoId` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`areaDoProfissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`areaDoProfissional` (
  `areaId` INT NOT NULL,
  `profissionalId` INT NOT NULL,
  PRIMARY KEY (`areaId`, `profissionalId`),
  CONSTRAINT `fk_area_has_profissional_area1`
    FOREIGN KEY (`areaId`)
    REFERENCES `mydb`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_area_has_profissional_profissional1`
    FOREIGN KEY (`profissionalId`)
    REFERENCES `mydb`.`transacionador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_area_has_profissional_profissional1_idx` ON `mydb`.`areaDoProfissional` (`profissionalId` ASC) VISIBLE;

CREATE INDEX `fk_area_has_profissional_area1_idx` ON `mydb`.`areaDoProfissional` (`areaId` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`areaDoProjeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`areaDoProjeto` (
  `areaId` INT NOT NULL,
  `vagaProfissionalId` INT NOT NULL,
  `vagaContratanteId` INT NOT NULL,
  PRIMARY KEY (`areaId`, `vagaProfissionalId`, `vagaContratanteId`),
  CONSTRAINT `fk_area_has_vaga_area1`
    FOREIGN KEY (`areaId`)
    REFERENCES `mydb`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_area_has_vaga_area1_idx` ON `mydb`.`areaDoProjeto` (`areaId` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`vaga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vaga` (
  `profissionalId` INT NOT NULL,
  `vagaId` INT NOT NULL,
  PRIMARY KEY (`profissionalId`, `vagaId`),
  CONSTRAINT `fk_profissional_has_vaga_profissional1`
    FOREIGN KEY (`profissionalId`)
    REFERENCES `mydb`.`transacionador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profissional_has_vaga_vaga1`
    FOREIGN KEY (`vagaId`)
    REFERENCES `mydb`.`Projeto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_profissional_has_vaga_vaga1_idx` ON `mydb`.`vaga` (`vagaId` ASC) VISIBLE;

CREATE INDEX `fk_profissional_has_vaga_profissional1_idx` ON `mydb`.`vaga` (`profissionalId` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
